{
 "title": "Recommendation System",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Average Popularity of Recommended Movies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(average_movie_popularity_total[5m])) / sum(rate(recommendation_requests_total{endpoint=\"/recommend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(recommendation_requests_total{instance=\"model-service1:8083\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(recommendation_requests_total{instance=\"model-service2:8083\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "1000 * rate(recommendation_request_duration_seconds_sum{endpoint=\"/recommend\"}[5m]) / rate(recommendation_request_duration_seconds_count{endpoint=\"/recommend\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[10m])\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Up Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "up{instance=\"load-balancer:8082\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{instance=\"model-service1:8083\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{instance=\"model-service2:8083\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Recommended Movie Popularity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(average_movie_popularity_total{instance=\"model-service1:8083\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(average_movie_popularity_total{instance=\"model-service2:8083\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}