global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'load-balancer'
    static_configs:
      - targets: ['load-balancer:8082']

  - job_name: 'model-service1'
    static_configs:
      - targets: ['model-service1:8083']

  - job_name: 'model-service2'
    static_configs:
      - targets: ['model-service2:8083']
